2022-04-25 16:45:54,352-ERROR-FILE:main.py-FUNC:<module>-LINE:167-(1044, "Access denied for user 'peng_yam'@'%' to database 'db_myanimelist'")
2022-04-25 16:47:04,070-ERROR-FILE:main.py-FUNC:<module>-LINE:167-(1044, "Access denied for user 'peng_yam'@'%' to database 'db_myanimelist'")
2022-04-25 16:47:47,202-ERROR-FILE:main.py-FUNC:<module>-LINE:167-(1044, "Access denied for user 'peng_yam'@'%' to database 'db_myanimelist'")
2022-04-25 16:48:39,081-ERROR-FILE:main.py-FUNC:<module>-LINE:167-(1044, "Access denied for user 'peng_yam'@'%' to database 'db_myanimelist'")
2022-04-25 17:10:37,333-ERROR-FILE:config.py-FUNC:_get_connection-LINE:48-Error: Database connection error! Please check your connection/username/password is correct!
2022-04-25 17:11:15,968-ERROR-FILE:config.py-FUNC:_get_connection-LINE:48-Error: Database connection error! Please check your connection/username/password is correct!
2022-04-25 17:15:18,891-ERROR-FILE:main.py-FUNC:<module>-LINE:167-(pymysql.err.OperationalError) (1049, "Unknown database 'peng_yam'")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-04-25 17:16:06,201-ERROR-FILE:main.py-FUNC:<module>-LINE:167-(pymysql.err.OperationalError) (1049, "Unknown database 'peng_yam'")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-04-25 17:17:41,765-ERROR-FILE:main.py-FUNC:<module>-LINE:167-(pymysql.err.OperationalError) (1049, "Unknown database 'peng_yam'")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-04-25 17:18:15,580-ERROR-FILE:main.py-FUNC:<module>-LINE:167-(pymysql.err.OperationalError) (1049, "Unknown database 'peng_yam'")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
